### ISSUE TITLE
SOLVED - DHT11 on my sonoff basic not show temperture

### ISSUE THREAD

**Issue by fgvicente** [arendst/Sonoff-Tasmota#1745]
I have connected a dht11 sensor in the gpio14 configure in modules the gpio but it does not show the values of the sensor

![image](https://user-images.githubusercontent.com/3626864/35523210-162bac94-04fd-11e8-8be8-62127874df2a.png)

![image](https://user-images.githubusercontent.com/3626864/35523409-8bec76e8-04fd-11e8-93f8-bc4c2ab5486f.png)

![image](https://user-images.githubusercontent.com/3626864/35523384-7c3a5dbe-04fd-11e8-96fd-d1da2836d8f6.png)

![image](https://user-images.githubusercontent.com/3626864/35523483-ba47e2b6-04fd-11e8-8b24-3f48bfbd59df.png)

I do not know what can be wrong. thanks in advance

**Comment by gtortone** [comment]
do you have a 4.7kohm resistor on DHT11 between 3.3V and DATA pin ?
(https://i0.wp.com/www.electrodummies.net/wp-content/uploads/2017/02/dht11-library-and-schematic-1.png)

**Comment by fgvicente** [comment]
mmm no. I will add and I will retest. thanks for response

**Comment by fgvicente** [comment]
already connect the resistance and neither does it. still does not show me the temperature. I even probe with the module of th but nothing.

![image](https://user-images.githubusercontent.com/3626864/35537453-04767c78-0529-11e8-9467-ce7ff08348a9.png)

![image](https://user-images.githubusercontent.com/3626864/35537477-1a774818-0529-11e8-9078-702eb8d9009f.png)
 
23:18:37 CMD: sensor
23:18:37 MQT: stat/home/baño/extractor/RESULT = {"Command":"Unknown"}

It's like there's no sensor. how can I test it

**Comment by gtortone** [comment]
I see you are using a quite old release. Try to upgrade it because there are some DHT11 issues solved in releases next to your...

**Comment by lobradov** [comment]
...also, not sure Tasmota will accept non-English characters in URL (ñ)... try replacing with regular n to see if it would be better.

//_ on phone

**Comment by app41** [comment]
really sure about connections? 
The devil is in the detail...

**SONOFF BASIC - CONNECTOR**
1 (close to the pushbutton)  Vcc
2 
3 
4 GND
5 data 
10k resistor between Vcc and data

**DHT CONNECTOR**
1  Vcc
2 data
3 
4 GND

by the way, I made a mistake in soldering a DHT22 last week, resistor was not connected to data
It run also without the resistor, maybe because of internal pull up in ESP

**Comment by app41** [comment]
try also to recompile the whole package changing the eeprom validation number
(#define CFG_HOLDER in user_config.h)
and then firmware again your sonoff with the new image
should you have something dirty in your configuration, you can clear it starting from a fresh eeprom reformatting
it is a 2-minute test...

**Comment by fgvicente** [comment]
im updated but still not working

![image](https://user-images.githubusercontent.com/3626864/35576899-f4027284-05be-11e8-83d6-0e3f06bdb6af.png)

**Comment by Jason2866** [comment]
Maybe the sensor is defect?!

**Comment by gtortone** [comment]
can you try the same sensor on a different board ? (e.g. Arduino, something else...)

**Comment by gtortone** [comment]
if you connect a simple led on GPIO14 does it work ?

**Comment by app41** [comment]
As last solution, try to cut/eliminate the resistor. I had similar experience few time ago, I don’t know why (maybe the sensor?) but it worked

 

Da: Jason2866 [mailto:notifications@github.com] 
Inviato: martedì 30 gennaio 2018 20:55
A: arendst/Sonoff-Tasmota <Sonoff-Tasmota@noreply.github.com>
Cc: Alberto <app41@virgilio.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [arendst/Sonoff-Tasmota] DHT11 on my sonoff basic not show temperture (#1745)

 

Maybe the sensor is defect?!

**Comment by fgvicente** [comment]
I already solved the problem. Review everything you do to me. the problem was bad welding in the sonoff. Thanks to everyone for their contributions
