### ISSUE TITLE
new hardware Teckin SP22 v1.4

### ISSUE THREAD

**Issue by Clooney82** [arendst/Sonoff-Tasmota#3950]
Hello together,

just bought a 4pack of Teckin SP22 because, I knew they were identical to Blitzwolf SHP2 / Gosund SP1.
I´ll got them yesterday an recognized that there is a new Version of them out now.
1. The are no more screwed together 
2. New HW Layout. TYWE2S based

Layout of new HW:
![img_7789](https://user-images.githubusercontent.com/13447523/46276957-f9e78780-c561-11e8-9da6-6e99686899e7.jpg)
![img_7794](https://user-images.githubusercontent.com/13447523/46276960-f9e78780-c561-11e8-9962-bacb6e112c25.jpg)

TYWE2S:
![img_7790](https://user-images.githubusercontent.com/13447523/46276958-f9e78780-c561-11e8-907f-86a200b10fb7.jpg)
![img_7792](https://user-images.githubusercontent.com/13447523/46276959-f9e78780-c561-11e8-9a08-d4a5e075de42.jpg)

Details:
![img_7796](https://user-images.githubusercontent.com/13447523/46276962-fa801e00-c561-11e8-9fd9-90b0b3e7e496.jpg)
![img_7797](https://user-images.githubusercontent.com/13447523/46276963-fa801e00-c561-11e8-9415-7472c42c0199.jpg)

![img_7795](https://user-images.githubusercontent.com/13447523/46276961-fa801e00-c561-11e8-85ca-7e27643659db.jpg)
![img_7798](https://user-images.githubusercontent.com/13447523/46276964-fa801e00-c561-11e8-9f6f-8f1529e71cbe.jpg)

Good new is, that i managed to get them to work.
For flashing I used this page: https://github.com/arendst/Sonoff-Tasmota/wiki/CE-Smart-Home---LA-WF3-Wifi-Plug-(TYWE2S)

For basic feature I used a generic board in configuration
GPIO1 Button 1
GPIO3 Led2i
GPIO13 Led1i
GPIO14 Relay1

after this was working I tried to figure out power measuring feature.
In sonoff_template.h I added a new entrie of for the Teckin based on the Blitzwolf setup.
After a few tried I got a working one.

>   { "TECKIN SP22v1.4",  // https://www.amazon.de/gp/product/B07D5V139R
>      GPIO_USER,        // GPIO00 Red Led (1 = On, 0 = Off)
>      GPIO_KEY1,        // GPIO01 Serial TXD and Button
>      GPIO_USER,        // GPIO02 Blue Led (1 = On, 0 = Off)
>      GPIO_LED2_INV,    // GPIO03 Serial RXD and Red Led (1 = On, 0 = Off)
>      GPIO_HLW_CF,      // GPIO04 BL0937 or HJL-01 CF power
>      GPIO_HLW_CF1,     // GPIO05 BL0937 or HJL-01 CF1 voltage / current
>      0, 0, 0, 0, 0, 0, // Flash connection
>      GPIO_HLW_SEL,     // GPIO12 BL0937 or HJL-01 Sel output
>      GPIO_LED1_INV,    // GPIO13 Blue Led (1 = On, 0 = Off)
>      GPIO_REL1,        // GPIO14 Relay (0 = Off, 1 = On)
>      0, 0, 0
>   }

Only Voltage was not shown correctly, so I calibrated it via console an VoltageSet

Hope this one will get official support.

BR, Jochen

**Comment by andrethomas** [comment]
Nice

Also see they have a nice way of installing a fuse inside the device ;)
![image](https://user-images.githubusercontent.com/470015/46281460-07573e80-c56f-11e8-97a6-63440b6955d2.png)

**Comment by arendst** [comment]
Pls give it a try and let me know if the power monitoring works as expected.

**Comment by Clooney82** [comment]
Hi, 
just tested your new Version, but it gives very strange power values.
So I compared your new Version and mine. Found out, that I use HJL based Values and you HLW Values.
After changings this, it looked good, only Voltage calibration needed to: 

> 07:49:04 CMD: VoltageSet 232.5
> 07:49:04 MQT: stat/sonoffplug03/RESULT = {"VoltageSetCal":1725}

xnrg_01_hlw8012.ino
Line 182
```
  if (BLITZWOLF_BWSHP2 == Settings.module) {
    hlw_power_ratio = HJL_PREF;
    hlw_voltage_ratio = HJL_UREF;
    hlw_current_ratio = HJL_IREF;
    hlw_ui_flag = HJL_SEL_VOLTAGE;
  } else {
    hlw_power_ratio = HLW_PREF;
```
changed to
```
  if (BLITZWOLF_BWSHP2 == Settings.module || TECKIN == Settings.module) {
```

**Comment by arendst** [comment]
Thx. Just fixed.

**Comment by Clooney82** [comment]
thanks, works great now.

**Comment by andrethomas** [comment]
@Clooney82 Awesome - if you have time please add some wiki information for this device so that other users can also use it easily. Thanks!

**Comment by docbobo** [comment]
@Clooney82, did you find a non-destructive way to open them up?

**Comment by matthewjporter** [comment]
Has anyone worked on the SP23 version?

**Comment by Clooney82** [comment]
@docbodo
Not completly, but you can use a flat screwdriver to get between both housing parts an lift it up until it „cracks“ the glue an than all around. With this was only one part of the housing is damaged. After opening you can Heat it up and form it back, so you don‘t see much damage. I also put a bit glue in the middle of all 4 sides after flashing worked to keep it closed and secured.

**Comment by pauledd** [comment]
@Clooney82 Hi,
the flash page you mentioned states I have to ground GPIO0 to flash the device...
Where exactly is GPIO0? Do they mean "IO0"?
I ask because the "official" documentation only contains GPIO_4,GPIO_5,GPIO_13...
https://fccid.io/2ANDL-TYWE2S/User-Manual/Users-Manual-3596121

**Comment by pauledd** [comment]
So I just connected 3.3V, GND, RX & TX to my USB2TTL adapter... RX to TX and TX to RX...
![20181027_165215](https://user-images.githubusercontent.com/12088907/47605700-1a441e00-da0a-11e8-8ed4-f37cc3713051.jpg)

Is it possible to verify that the serial connection is successful? 
If I open a terminal (screen /dev/ttyUSB0) and I connect the 3.3V to the board I get a line of garbled characters printed. If I press the button on the board while connecting the power I dont get any output..

**Comment by pauledd** [comment]
Ok I made some progress...
The problem was I did not disconnect the whole USB-Serial adapter but only the 3,3V cable...
As I wired  "IO0" to GND, plugged in the USB-Serial adapter and issuing the command to first read the flash memory for backup:

```
sudo esptool.py --port /dev/ttyUSB0 read_flash 0x00000 0x100000 image1M.bin
esptool.py v2.6-beta1
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: dc:4f:22:d4:6b:e0
Uploading stub...
Running stub...
Stub running...
^[[C1048576 (100 %)
1048576 (100 %)
Read 1048576 bytes at 0x0 in 94.2 seconds (89.0 kbit/s)...
Hard resetting via RTS pin...
```
So far... going into flash mode again...
Then I erased the flash

```
sudo esptool.py --port /dev/ttyUSB0 erase_flash
esptool.py v2.6-beta1
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: dc:4f:22:d4:6b:e0
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 3.6s
sudo esptool.py --port /dev/ttyUSB0 erase_flash
esptool.py v2.6-beta1
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: dc:4f:22:d4:6b:e0
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 3.6s
Hard resetting via RTS pin...
```

going into flash mode again... 
Then I flashed the "sonoff-minimal.bin":
```
sudo esptool.py --port /dev/ttyUSB0 write_flash -fs 1MB -fm dout 0x0 sonoff-minimal.bin 
esptool.py v2.6-beta1
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: dc:4f:22:d4:6b:e0
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 346240 bytes to 246184...
Wrote 346240 bytes (246184 compressed) at 0x00000000 in 22.7 seconds (effective 121.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

going into flash mode again... 
Then I flashed the "sonoff.bin":
```
sudo esptool.py --port /dev/ttyUSB0 write_flash -fs 1MB -fm dout 0x0 sonoff.bin 
esptool.py v2.6-beta1
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: dc:4f:22:d4:6b:e0
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 482512 bytes to 330006...
Wrote 482512 bytes (330006 compressed) at 0x00000000 in 30.2 seconds (effective 127.7 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

Then I disconnected power and reconnected power but nothing
happens if I press the button...
Do I have to reassemble the plug and test it on mains ac?
Or should it work with 3.3V too?

**Comment by pauledd** [comment]
Well I guess I have to compile a customized binary instead of using the pre-compiled ones?

**Comment by pauledd** [comment]
Sorry for polluting this thread. I made more progress.
My device is now running the new firmware. The problem was maybe a power/voltage issue and binary issue.
Since I powered the 3.3V from my lab power supply and not from my USB-TTY Adapter the device
started to blink blue. It showed as a new wifi device on my android phone but seemed to be in a boot loop because it disapeared ever 4 secs. I then compiled the binary myself with arduino ide.

I made changes as @Clooney82 described in his first post in the file Sonoff_template.h,
added the new Teckin section and also added the two new GPIOS GPIO_HLW_CF1,
  GPIO_HLW_SEL in "ProgramSelectablePins" at the end but before "GPIO_MAX".
I also added "TECKIN22P" in "SupportedModules" at the end but before "MAXMODULE".

Then I added my AP details in my_user_config.h, compiled and erased and flashed and then the device was reachable in my LAN. I will now reassemble the plug and see if everything else works.

**Comment by pauledd** [comment]
The plug works now on AC, I can switch it. But how can I show power consumption? There is no such option in the web interface...

**Comment by pauledd** [comment]
Problem solved: https://github.com/arendst/Sonoff-Tasmota/issues/4204
mission accomplished.
bye

**Comment by philipp2310** [comment]
Is there any chance to flash it "over the air"?
The two sp22 I got don't even offer a smallest slit to get the housing open :/

**Comment by matthewjporter** [comment]
> @matthewjporter
> Here is the ESP module in the SP23 (UK version). Just flashed it successfully. To get at the pins on the module, you need to unsolder the Live & Neutral connections on the main PCB so you can remove the PCB from the base.
>
@ocl80 Thanks for the update, Will give it a bash

How did you get it open, Hot air gun and sharp edge tool i guess, did it destroy the case?

Does it still do the power monitoring?

Cheers

**Comment by ocl80** [comment]
@matthewjporter I don't have a hot air gun so just a sharp edge tool in my case. I might have been lucky, but with a bit of patience it opened nicely and you wouldn't know now it is back together. 
In Tasmota it is configured as a BlitzWolf SHP2, and the energy & power metrics seem to work, although on mine the voltage is off somewhat.

![image](https://user-images.githubusercontent.com/44789816/48097959-3d917900-e213-11e8-81ba-36c1f8efe56a.png)

**Comment by matthewjporter** [comment]
Hi All

Just to update on the "dismantling" of the Teckin SP23. I have taken some pics as I go as it may help so here they are:

This is the Unit I have and is currently on Amazon and at £10 each is not bad for a power monitoring plug https://www.amazon.co.uk/TECKIN-Monitoring-Function-Anywhere-Required/dp/B07D7BH6N8/ref=sr_1_1?ie=UTF8&qid=1541589149&sr=8-1&keywords=teckin  
![2018-11-07 10 25 07](https://user-images.githubusercontent.com/15786074/48126875-39e50d00-e27a-11e8-8b58-b4da91a5ef06.jpg)

![2018-11-07 10 25 12](https://user-images.githubusercontent.com/15786074/48127996-0d7ec000-e27d-11e8-9ef7-733d1f4db591.jpg)

This is what I used to get into it (Heat gun helped as it is glued together on the edges)
![2018-11-07 11 07 01](https://user-images.githubusercontent.com/15786074/48128273-d957cf00-e27d-11e8-9d93-bcb72830318c.jpg)


Only slight damage to the edging but heat gun will fix when closing up
![2018-11-07 10 11 18](https://user-images.githubusercontent.com/15786074/48128271-d361ee00-e27d-11e8-8b43-66a464187c90.jpg)

This is what I found on the inside. This seems to be a new design!
![2018-11-07 10 12 17](https://user-images.githubusercontent.com/15786074/48128245-c513d200-e27d-11e8-8926-187deb8feaf8.jpg)
![2018-11-07 10 12 28](https://user-images.githubusercontent.com/15786074/48128246-c513d200-e27d-11e8-8b7b-6676e64e6c93.jpg)
![2018-11-07 10 22 37](https://user-images.githubusercontent.com/15786074/48128247-c513d200-e27d-11e8-9a69-203b90914286.jpg)

I noticed that it is not using the TYWE2S chip, but is still esp8266 based

After de-soldering the Live & Neutral the board came right off
![2018-11-07 10 43 14](https://user-images.githubusercontent.com/15786074/48128489-8894a600-e27e-11e8-8ec1-7ab041cfcaff.jpg)
![2018-11-07 10 43 18](https://user-images.githubusercontent.com/15786074/48128490-892d3c80-e27e-11e8-8c57-4f9bd19fd83f.jpg)
![2018-11-07 10 42 58](https://user-images.githubusercontent.com/15786074/48128491-892d3c80-e27e-11e8-8cbb-5412408867a8.jpg)
![2018-11-07 10 43 02](https://user-images.githubusercontent.com/15786074/48128493-892d3c80-e27e-11e8-8cb6-69d1add6984a.jpg)
![2018-11-07 10 43 09](https://user-images.githubusercontent.com/15786074/48128495-892d3c80-e27e-11e8-9def-270ee35ae27c.jpg)

Next steps are a work in progress:
1. line up the board and cut a hole in the bottom
2. Make a template to drill holes for my other units to avoid opening up
![2018-11-07 11 18 34](https://user-images.githubusercontent.com/15786074/48128613-e9bc7980-e27e-11e8-8f56-f9fe16c4e266.jpg)
3. Figure out what is what on this new chip and which is GND, TX, RX & GPIO0

Hope this helps right now for anyone else looking at updating these units

**Comment by BubbaFatAss** [comment]
Hi there,

I also bought a 4 pack of SP23's from Amazon, and was annoyed to find that they were sealed shut.  I didn't do as good a job as you did about opening them, but in case you haven't got the pinouts yet, I've worked these out and have flashed mine with the standard SHP2 binary of Espurna which works nicely for me.  The pinouts are as follows:
![sp23 pinout](https://user-images.githubusercontent.com/1834077/48222448-828ceb00-e38c-11e8-89a4-60851e07ba4a.jpg)
Sorry, I forgot to mark which of the two pads were RX or TX, but at least that's usually easy to swap round, and they're to nice easily identifiable solder pads.  I have three more to flash, so I'll update this with the correct RX and TX pins when I do the next one.

Cheers

Andy

**Comment by matthewjporter** [comment]
@BubbaFatAss 

Many thanks, Saved me the time working out the pins

I have 12 of these and a mate has a few more so is why I am making a template to drill the holes and will possibly even do a 3d print template

**Comment by BubbaFatAss** [comment]
I considered printing a new housing for them, but the first one has mostly heatgunned back in to place, with a bit of epoxy where necessary.  I've just desoldered my 2nd and am about to flash it - the first is working very nicely.  For £10 a pop for such a compact design of energy monitoring smart plug I'm prepared to do a bit of messing around.  Not quite sure I could stomach 12 though! :)

**Comment by matthewjporter** [comment]
@ £10 a pop is why I have a 12 of them :) as they are the cheapest and easiest way to convert to smart sockets and with the ability to monitor power consumption is just an added bonus

Will post my template once done but no guarantee the hardware wont change as they do with these things

**Comment by BubbaFatAss** [comment]
I managed to get into the last two in a much cleaner way by hitting the sides hard-ish with a hammer.  This cracked the glue, and allowed the parts to be separated with a spudger without destroying the casing.  I've previously used Sonoff S20 / s26's which are nicer but don't monitor power and aren't as highly rated.

**Comment by m24andrew** [comment]
> Will post my template once done but no guarantee the hardware wont change as they do with these things

I'd be interested in a copy of the template so I can print new cases for the 4 I bought!

**Comment by matthewjporter** [comment]
Hole drilling template coming along however am on the second case I have had to crack open :)

@BubbaFatAss I might just try that trick with the hammer if my templates does not work out but I bet by the time I get to number 12 I will be spot on

First attempt - went for the big RX/TX solder pads and had lined up but kept moving around so tried superglue and hot glue to keep pins in place but very hit and miss on the connection
![2018-11-10 19 24 57](https://user-images.githubusercontent.com/15786074/48305210-8d778500-e51e-11e8-8c3a-da9963afe827.jpg)
![2018-11-09 16 41 03](https://user-images.githubusercontent.com/15786074/48305394-8ef67c80-e521-11e8-849f-0e1fa3187dc4.jpg)
![2018-11-09 16 41 15](https://user-images.githubusercontent.com/15786074/48305397-987fe480-e521-11e8-962d-69f44cd25755.jpg)
![2018-11-09 16 48 17](https://user-images.githubusercontent.com/15786074/48305365-30310300-e521-11e8-86e3-ea53f8ef500f.jpg)

Second attempt -  Trying for the chip connectors themselves
![2018-11-10 19 25 14](https://user-images.githubusercontent.com/15786074/48305211-936d6600-e51e-11e8-9e06-333b724fc45b.jpg)

Update on the pin-out:
![2018-11-07 10 43 14](https://user-images.githubusercontent.com/15786074/48305184-06c2a800-e51e-11e8-9c53-3706ed33864f.jpg)

Note, that I have found that you can connect directly to the neutral plug leg as the ground so will only need 4 holes to be drilled and a crocodile clip onto the neutral plug leg

Now for the Flashing - I use ESPEasy Flasher
1. Download the sonoff-basic.bin from github
2. Run ESPEasy Flasher, select the bin (Must be in the same directory as FlashESP8266.exe)
3. Connect to "sonoff-xxxx" SSID
4. Open 192.168.4.1
5. Point browser to IP assigned by your DHCP server (in my case I just fire up TasmoAdmin in HASSIO and do a scan)
6. Configure unit as a "BlitzWolf SHP2"
7. Complete MQTT etc etc as per your requirements

Hey Presto
![2018-11-09 18 42 45](https://user-images.githubusercontent.com/15786074/48305418-df6dda00-e521-11e8-804a-52c66e0a0489.jpg)

**Comment by matthewjporter** [comment]
There is now an option for "Teckin" in the Module type, Testing the two modules to see if I can notice a deference, but both seem to work and have power monitoring

**Comment by matthewjporter** [comment]
OK, So the "Teckin" module does not work. The on/off button does not work and even the "toggle" on the webpage does not work

No power usage either, Switched back to "BlitzWolf SHP2" and works on reboot

**Comment by m24andrew** [comment]
@matthewjporter Wow, amazing...I have just got a pack of four of these plugs so would be interested in your .stl to sort mine out once you are done...I'll keep watching your great work!

**Comment by matthewjporter** [comment]
@m24andrew 
Here is my current template in stl [teckin-sp23_pinout_hole_template.zip](https://github.com/arendst/Sonoff-Tasmota/files/2568781/teckin-sp23_pinout_hole_template.zip)

I have not put the holes in it yet as I have got them in roughly the right place so the digital calipers have just come out to play - Told the wife they would come in handy, same as the 3D printer :)

I have gone from this where I cracked it open and cut a nice big hole
![2018-11-10 21 10 02](https://user-images.githubusercontent.com/15786074/48306084-670d1600-e52d-11e8-83e0-d36b6bb6b617.jpg)
to  this with it being cracked open and two smaller holes
![2018-11-10 21 10 10](https://user-images.githubusercontent.com/15786074/48306085-6e342400-e52d-11e8-9ed3-7c880b00a33b.jpg)
to this with just 4 drill holes
![2018-11-10 21 10 18](https://user-images.githubusercontent.com/15786074/48306087-75f3c880-e52d-11e8-83dc-9f92ec029e1e.jpg)

I fear the top right hole is just a little low and needs moving up so am printing 4 base templates as attached and will then put the final holes in the stl

This would have been easier if you could just do an OTA update via the TUYA or the Smart Life app :(

Good job the plugs are still usable, and in my eyes even more so with the awesome Tasmota firmware on them

**Comment by m24andrew** [comment]
I know, I did all my old sonoff sockets OTA from the start but one missed out due to the firmware change they made!  Thanks for the information, I love these little plugs and as you say, when they have Tasmota they will be great.  Keep me posted about your final .stl with the holes and maybe I can save cracking one.  I appreciate all your time and ingenuity!

**Comment by matthewjporter** [comment]
First Flash done without cracking the case open

Do not move a muscle
![2018-11-10 22 03 49](https://user-images.githubusercontent.com/15786074/48306684-cc183a00-e534-11e8-89b9-c8a29b1a1de2.jpg)

Just waiting for the printer to complete and then new holes in the template and attempt #4

**Comment by BubbaFatAss** [comment]
> OK, So the "Teckin" module does not work. The on/off button does not work and even the "toggle" on the webpage does not work
> 
> No power usage either, Switched back to "BlitzWolf SHP2" and works on reboot

Yeah, I think the Teckin module is for the SP22 plugs that use the TYWE2S chip instead of the ESP8266 that the SHP2 / SP23 uses.  Can confirm mine are now all flashed and comfortably working with HomeAssistant via Espurna.

It's a real shame these aren't done up with screws, would make it so much easier to get into.  The template looks really useful though - if I have any more to do I'll grab it and save bashing them with a hammer.

Cheers

Andy

**Comment by dmartingarcia** [comment]
I have a SP22 right now connected, and in DHCP gives a ESP-**** hostname. Can some versions exists of the same model? @BubbaFatAss

**Comment by dmartingarcia** [comment]
not many versions but just many hardware specifications in terms of chip brand.

**Comment by matthewjporter** [comment]
Thanks @m24andrew

Just ordered some pogo pins to make the connection easier as thes can be set in the template and just pushed into the holes

My philosophy is that I would rather spend a few hours (days in this case) working on a process that makes a long repetitive task like this as simple as possible and make it a simple job to do than the original task

In this case remove the hassle that is cracking open the case and then trying to put it all back neatly when all you have to do is drill 4 holes, insert some PoGo pins and flash

Again, why these manufactures don’t have an OTA update or even extend the pin-outs for easy access is beyond me

Surely they know they are being made for the iOT market and we like to play with these things

Side thought, might be worth trying to contact the manufacture and get the firmware put on at source :)

**Comment by m24andrew** [comment]
I am sure they tried with itead but got nowhere. 
I’ll order some pins too from amazon. Is the template with holes done or are you still tweaking? Thanks, Andrew

**Comment by matthewjporter** [comment]
Very hit and miss at the moment, Will update when my PoGo pins arrive

Might need to crack open another one to ensure holes are 100% aligned :(

**Comment by m24andrew** [comment]
@matthewjporter that’s a shame having to open another one. I look forward to your updates and again, great work!

**Comment by NicoWallmeier** [comment]
The new Teckin SP22 are working fine for me in general. The only problem I have is that the power computation is not working accurately. The measured voltage I could correct with the VoltageSet command. But the command PowerSet 60.0 does not work - it still shows 51 W instead of 60 W (I'm using a 60W bulb)...

**Comment by arendst** [comment]
Play with currentset too

**Comment by milobt** [comment]
@matthewjporter how did you get on aligning holes with a template?
Do you have an updated STL yet that I can try?
Thanks.

**Comment by matthewjporter** [comment]
> @matthewjporter how did you get on aligning holes with a template?
> Do you have an updated STL yet that I can try?
> Thanks.

From what I can see they are aligned after a few adjustments, just not getting the best connection with some 1mm gauge wire poked in the hole :(

PoGo pins arriving today so will be testing later

Once I have confirmed, will upload the STL with the correct holes for drilling and the PoGo pins

**Comment by matthewjporter** [comment]
PoGo pins arrived and after a bit of fiddling I have now flashed 3 sockets
![2018-11-13 11 21 14](https://user-images.githubusercontent.com/15786074/48414015-5af9a200-e741-11e8-92bb-73aaff92626c.jpg)
Notice the green wire (5v in my case) is set shorter than the yellow (GND). I found that connecting GND to GPIO0 before 5V is critical to getting the device into flash mode and with the PoGo pins this makes it easier

Best also the connect/push in the RX/TX first before connecting power
![2018-11-13 11 20 54](https://user-images.githubusercontent.com/15786074/48414020-5fbe5600-e741-11e8-9368-91d394dd2a00.jpg)

Not happy with the size of the hole as I have 1.5mm drill bit and 1.02mm PoGo pins so going to test with a 1mm drill bit but cant find my 1mm drill bit, thankfully a certain online retailer will deliver by tomorrow

**Comment by milobt** [comment]
I was thinking of fixing the pogo pins into the 3D printed jig.
You could still set the 5V pin slightly higher and then push the jig down to make connection on all pins.
This way they would stay straight and hopefully in contact with the pads.

**Comment by matthewjporter** [comment]
> I was thinking of fixing the pogo pins into the 3D printed jig.
> You could still set the 5V pin slightly higher and then push the jig down to make connection on all pins.
> This way they would stay straight and hopefully in contact with the pads.

Exactly what the plan is. Now I have them set at the right height am going to fix in place with some hot glue

Making the hole smaller is just me being a bit OC as they move around a tad

If I was doing hundreds of these, I might change the template to have a block to put the PoGo pins in and but since I only have twelve or so hot glue will do :)

**Comment by matthewjporter** [comment]
Interesting, 

As i feared before, here is another Teckin SP23 socket, but it has different printing on it.
![2018-11-13 14 29 41](https://user-images.githubusercontent.com/15786074/48419841-d9117500-e750-11e8-95e8-7725a1ae5f6a.jpg)

I wonder what the insides look like, Maybe the same as @ocl80 posted as they were the first ones I 
purchased

Time to break out the hammer, but first let's drill some holes to check
![2018-11-13 14 29 41](https://user-images.githubusercontent.com/15786074/48419961-2beb2c80-e751-11e8-8719-4293b5001fae.jpg)

Yep, Nothing under those holes. I only have 4 so its "Hammer Time"

Bummer

**Comment by milobt** [comment]
Mine have the same print as the original ones you were flashing, so your pin positions should hopefully be good for me.

**Comment by matthewjporter** [comment]
Looks to be the same board as @ocl80 

Wont be hard to get the pins holes for it now I have it open and the fact its not at an angle but parallel with the casing

**Comment by m24andrew** [comment]
@matthewjporter What a pain!  I have the newer ones with the holes as in your template.  You are doing a great job, I hope I can sort mine easily as I have just stuffed two of my old sockets trying to update Tasmota OTA...
By the way, are you using 5v vcc?

**Comment by matthewjporter** [comment]
> @matthewjporter What a pain! I have the newer ones with the holes needed as per your template. You are doing a great job, I hope I can sort mine easily, as I have just stuffed two of my old sockets trying to update Tasmota OTA...
> By the way, are you using 5v for VCC?

Interested how you managed the OTA on these or was it other brands?

Here is the FTDI I am using. Connected to 5V
![2018-11-13 16 58 34](https://user-images.githubusercontent.com/15786074/48429875-eab14780-e765-11e8-9d61-2aaf519c0bd1.jpg)
![2018-11-13 16 58 41](https://user-images.githubusercontent.com/15786074/48429876-eab14780-e765-11e8-867b-9037ada2765c.jpg)

**Comment by m24andrew** [comment]
> Interested how you managed the OTA on these or was it other brands?

other brands that were Sonoff clones...it was once possible to upgrade to Tasmota OTA right from the start.  They are almost impossible to dismantle without breaking them so OTA was great.  Going from 5.14 to 6.30 worked for the minimal but failed on the classic and now they are useless...
> 
> Here is the FTDI I am using. Connected to 5V

Ah ok, I've always used 3.3v, interesting to know.

**Comment by matthewjporter** [comment]
Holes drilled, checked and flashed
![2018-11-13 17 00 29](https://user-images.githubusercontent.com/15786074/48430405-2b5d9080-e767-11e8-88ef-16cfbb83b5c1.jpg)
Messy pic, Sorry

Problem with this one is that its a different chip and circuitry

I will upload two STL for the different versions

**Comment by matthewjporter** [comment]
> Ah ok, I've always used 3.3v, interesting to know.

I tried 3.3V and the 5V and just left it on 5V so is the only reason its on that :)

**Comment by matthewjporter** [comment]
Success first go
![2018-11-13 17 38 44](https://user-images.githubusercontent.com/15786074/48432633-de7cb880-e76c-11e8-8f1c-e11017b05444.jpg)

I will work on the STL now, I promise

**Comment by matthewjporter** [comment]
> @matthewjporter any success with the STL templates?

Sadly no, Day job got in the way as I had to do two exams, Hopefully this afternoon

**Comment by milobt** [comment]
Here's an STL of the jig I managed to pull together, using @matthewjporter photos as a guide. With a bit of fine tuning, I managed to get it accurate enough to drill 1mm holes.

![img_5945](https://user-images.githubusercontent.com/391981/48629592-f4c78600-e9b1-11e8-8404-01da1f056afc.JPG)

One side of the jig has V,G,R,T (Vcc, GND, RXD, TXD).
These holes can be used for your test pins.
![img_5946](https://user-images.githubusercontent.com/391981/48629598-f6914980-e9b1-11e8-8278-ae3bc6fddc73.JPG)

If you flip it over, there is the word "DRILL", which indicates the use of the holes in the circle that can be used as guides to drill holes, which ever size you feel necessary.
![img_5947](https://user-images.githubusercontent.com/391981/48629605-f7c27680-e9b1-11e8-930f-8d8d0dcad836.JPG)

[Teckin_SP23_Smart_Plug_Template-New_PCB.zip](https://github.com/arendst/Sonoff-Tasmota/files/2589746/Teckin_SP23_Smart_Plug_Template-New_PCB.zip)

I currently, have no need for the older PCB hole arrangement, so maybe @matthewjporter can advise on these.

Thanks to everyone that contributed to this thread.

**Comment by matthewjporter** [comment]
> Here's an STL of the jig I managed to pull together, using @matthewjporter photos as a guide. With a bit of fine tuning, I managed to get it accurate enough to drill 1mm holes.
> 
> ![img_5945](https://user-images.githubusercontent.com/391981/48629592-f4c78600-e9b1-11e8-8404-01da1f056afc.JPG)
> 
> One side of the jig has V,G,R,T (Vcc, GND, RXD, TXD).
> These holes can be used for your test pins.
> ![img_5946](https://user-images.githubusercontent.com/391981/48629598-f6914980-e9b1-11e8-8278-ae3bc6fddc73.JPG)
> 
> If you flip it over, there is the word "DRILL", which indicates the use of the holes in the circle that can be used as guides to drill holes, which ever size you feel necessary.
> ![img_5947](https://user-images.githubusercontent.com/391981/48629605-f7c27680-e9b1-11e8-930f-8d8d0dcad836.JPG)
> 
> [Teckin_SP23_Smart_Plug_Template-New_PCB.zip](https://github.com/arendst/Sonoff-Tasmota/files/2589746/Teckin_SP23_Smart_Plug_Template-New_PCB.zip)
> 
> I currently have no need for the older PCB hole arrangement, so maybe @matthewjporter can advise on these.
> 
> Thanks to everyone that contributed to this thread.

Great work, Sorry my time ran away with me.

I will look at adding the other model to the same STL as I found that they do no overlap and have it on a single print out

**Comment by pauledd** [comment]
I just want to mention my Europe-Plug Teckin SP22 v1.4 flashed device consumes ~0.8W turned off and ~1.3W turned on, just if someone wants to compare...

**Comment by n3m3s1s** [comment]
Hello everyone maybe someone can help me a little with these devices. I am not able to get esptool connected to that device. My hardware is an arch linux laptop and as you can see in the pictures below I tried using an arduino as power source and a ch341-uart jumped to 3.3v to try and get a connection. I tried as well by wiring the arduinos RESET to GND since the atmel is practically disabled then.
I plugged in the CH341, pressed the button on the SP22 and then connected 3.3V from the arduino. If I open the ch341 console in screen I get some garbage on booting. So I assume something must be going on. Anyways whenever I try to use esptool this happens:
```
esptool --port /dev/ttyUSB1 chip_id  
esptool.py v2.5.1
Serial port /dev/ttyUSB1
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to Espressif device: Timed out
waiting for packet header
```
Off course RX <-> TX and vice versa.

Any ideas what could be wrong?

![img_20181124_112201](https://user-images.githubusercontent.com/2639374/48967479-5d7db680-efe1-11e8-9446-8b4835c62bdc.jpg)
![img_20181124_112234](https://user-images.githubusercontent.com/2639374/48967482-62426a80-efe1-11e8-887e-827ac0fd8c39.jpg)
![img_20181124_112215](https://user-images.githubusercontent.com/2639374/48967483-640c2e00-efe1-11e8-989d-b24b713174b7.jpg)

**Comment by matthewjporter** [comment]
Have you tried swapping the tx and tx?

Sent from my iPhone

On 24 Nov 2018, at 11:08, n3m3s1s <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello everyone maybe someone can help me a little with these devices. I am not able to get esptool connected to that device. My hardware is an arch linux laptop and as you can see in the pictures below I tried using an arduino as power source and a ch341-uart jumped to 3.3v to try and get a connection. I tried as well by wiring the arduinos RESET to GND since the atmel is practically disabled then.
I plugged in the CH341, pressed the button on the SP22 and then connected 3.3V from the arduino. If I open the ch341 console in screen I get some garbage on booting. So I assume something must be going on. Anyways whenever I try to use esptool this happens:

esptool --port /dev/ttyUSB1 chip_id
esptool.py v2.5.1
Serial port /dev/ttyUSB1
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to Espressif device: Timed out
waiting for packet header


Off course RX <-> TX and vice versa.

Any ideas what could be wrong?

[img_20181124_112201]<https://user-images.githubusercontent.com/2639374/48967479-5d7db680-efe1-11e8-9446-8b4835c62bdc.jpg>
[img_20181124_112234]<https://user-images.githubusercontent.com/2639374/48967482-62426a80-efe1-11e8-887e-827ac0fd8c39.jpg>
[img_20181124_112215]<https://user-images.githubusercontent.com/2639374/48967483-640c2e00-efe1-11e8-989d-b24b713174b7.jpg>

**Comment by pauledd** [comment]
Have you tried to enable flash mode (IO0 (for the european plug) to GND at powerup) ? I cant remember if it was necessary to communicate with the device...

**Comment by matthewjporter** [comment]
Good shout, I had to ground gpio0 on all the ones I have done

Sent from my iPhone

On 24 Nov 2018, at 15:51, pauledd <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried to enable flash mode (IO0 (for the european plug) to GND at powerup) ? I cant remember if it was necessary to communicate with the device...

**Comment by m24andrew** [comment]
Does anyone have a circuit diagram for the SP23 or know where else GPIO0 can also be pulled to zero on the board...I have pulled off the track and need another point to bring it down?  Thanks

**Comment by n3m3s1s** [comment]
> 
> Have you tried swapping the tx and tx?


Yes I have.



> 
> 
> Have you tried to enable flash mode (IO0 (for the european plug) to GND at powerup) ? I cant remember if it was necessary to communicate with the device...

Yeah I did that. too but with no result. May I ask what Hardware you are using to flash the ESPs?

**Comment by m24andrew** [comment]
I am using this USB to TTL adapter and VSCode to upload the firmware.  Works a treat.  In the end I am just hitting them with a hammer to open them up as they open so easily and cleanly that way.  I printed the template and it didn't work for me.  I then stick them back together and you would never know they had been opened...
![img_2602](https://user-images.githubusercontent.com/33388430/48979889-6641bb80-f0b9-11e8-9aec-130b9ddf894c.jpg)

**Comment by n3m3s1s** [comment]
I really think about buying a different USB to TTL but I don't think this really is the issue. Can I verify in some way that my power supply is working and providing sufficient power? I start to think that this might be one of my problems.
I also might try simply flashing it without using esptool before. Is that how you did it?

**Comment by matthewjporter** [comment]
I had a cheap o chines one that for most things worked fine but when I started to flash my sonoff device it was very hit and miss and that was with the proper headers on the device so no soldering etc. I bought the one I pictured above and have not had a missed flash since then

**Comment by m24andrew** [comment]
@n3m3s1s I couldn't get esptool to work, I tried using my Mac and a raspberry PI but nothing same output as you.  I have Visual Studio Code and Platform installed on it.  Just loaded up the Tasmota folder, made the relevant adjustments and worked fine for 8 plugs.

**Comment by milobt** [comment]
Anyone tried the Slitinto smart plug [Amazon](https://www.amazon.co.uk/gp/product/B07GDB8W95/ref=ox_sc_act_title_1?smid=A249A840W8VRTX&psc=1)

They look just link the Teckin ones, only with an LED on the front surface?

**Comment by m24andrew** [comment]
I bought 8 slitinto plugs in a flash sale. They are slightly different shape to Teckin ones. The board is the one in the photo I published yesterday and  they are easily flashed. I use the blitz wolf config and they all work great.

**Comment by m24andrew** [comment]
I crackled them all with a hammer and they went back good as new

**Comment by milobt** [comment]
Here's a template for the older Teckin plugs with (vertically aligned ESP8266 chip), plus the Slitinto plugs.
As with my previous jig design, one side can be used as a drill jig, the other for programming.
This design has holes for ~0.7mm test pins and also sockets for jumper wire headers.

![img_6033](https://user-images.githubusercontent.com/391981/49158632-8de38e80-f31a-11e8-891f-52725db78ab6.JPG)
![img_6034](https://user-images.githubusercontent.com/391981/49158635-8f14bb80-f31a-11e8-8457-ca21a3593168.JPG)

[Slitinto(NX-SM110)-Smart_Plug_Template.zip](https://github.com/arendst/Sonoff-Tasmota/files/2624926/Slitinto.NX-SM110.-Smart_Plug_Template.zip)

**Comment by szepnorbee** [comment]
Has anyone experienced even more random restarts with this module? (Teckin SP22) I have two of these modules and every day, at least once a night, they restart. Restart Reason is always: Power on. Flashed first with sonoff minimal then sonoff full image. Then custom image with many features disabled, but the problem remain. Free Program Space: 516kB ;Free Mamory: 27kB

**Comment by mgaida11** [comment]
Just bought three of SP22 (EU-plug), glued and without screws :-( 
It is a real pain to open it. A sharp cutter knife diesn't help much. This is the first Chinese plastic device that has gap tolerances of a BMW. 
Is there no way to flash using OTA?

**Comment by n3m3s1s** [comment]
> Is there no way to flash using OTA?
Did you even read the posts above you? This whole "thread" is about how to flash that device. You can either open it or even flash without opening depending on the conditions of your device and your equipment.

**Comment by matthewjporter** [comment]
@mgaida11

At the mo there is no OTA from the official firmware that I have seen

**Comment by m24andrew** [comment]
@mgaida11 

It's not that hard cracking them open with a solid rubber mallet...I have just done 4 more very easily and went back together no problem.

[https://www.gooutdoors.co.uk/hi-gear-rubber-mallet-12oz-p360534](url)

The original Sonoff device that connected via Ewelink was able to flash OTA directly but that stopped being possible after a certain firmware release and the conversation about it continues today....

Have a read here..

[https://github.com/mirko/SonOTA](url)

**Comment by mgaida11** [comment]
Cracking with a rubber mallet? It sounds pretty bizarre to me. How do you do that, please?

**Comment by m24andrew** [comment]
It isn't that bizarre...
Place the socket on a cloth on a hard surface or the floor:
Firmly hit the plug on the border of the base and the main part of the plug:

![1](https://user-images.githubusercontent.com/33388430/50728891-d3b92100-1128-11e9-99c2-23aa0e1bd1ee.JPG)

Rotate round and continue firmly hitting until the base releases from there main plug;

![2](https://user-images.githubusercontent.com/33388430/50728894-dae02f00-1128-11e9-9510-388ab7405ab7.JPG)
![3](https://user-images.githubusercontent.com/33388430/50728896-de73b600-1128-11e9-9ba4-6c06dbaaca3c.JPG)
![4](https://user-images.githubusercontent.com/33388430/50728897-e03d7980-1128-11e9-9cb8-0731ba3ca80f.JPG)
![5](https://user-images.githubusercontent.com/33388430/50728899-e3386a00-1128-11e9-8794-48d53f5ffd3f.JPG)
![6](https://user-images.githubusercontent.com/33388430/50728900-e7648780-1128-11e9-816c-ffa9750e8fc9.JPG)

flash the firmware the stick the base back in with hot glue and good as new...

![7](https://user-images.githubusercontent.com/33388430/50728904-f3e8e000-1128-11e9-849c-c83217646d76.JPG)

I have done 16 of these now and all working perfectly with the Tasmota firmware...

![screen shot 2019-01-05 at 20 33 39](https://user-images.githubusercontent.com/33388430/50728940-6d80ce00-1129-11e9-8166-642876d4f85b.jpg)

And now I have updated them all OTA with the latest firmware version too.

**Comment by beveradb** [comment]
Thanks so much for clearly explaining the rubber mallet technique for getting these open cleanly @m24andrew - I don't own a heat gun so was worried I'd have to claw at these plugs with a blade to open them, leaving them looking scrappy/unsafe (to my wife).
I actually didn't own a rubber mallet either, but realised my shower rail end plug fits perfectly over the end of my claw hammer 😂
It worked a treat, and I've now got 8 open Slitinto (NX-SM110) plugs with no visible damage 👍 

![image](https://user-images.githubusercontent.com/757713/50778627-54e1f680-1296-11e9-888d-a62ec4dd8756.png)

However, before I get out my soldering iron (it's been a while) and start unsoldering the Live & Neutral so I can remove the PCB, since you've done 16 now I thought I'd ask if you had any tips for doing this cleanly?

My worry is that I won't resolder it well enough for it to make a reliable connection, and at some point in the future, there will more current going through the plug than my poor solder joint can cope with and it'll be a safety hazard 😟

**Comment by m24andrew** [comment]
No warriors, I’m glad you got them all open ok!
Desoldering them is a bit of a pain. I have a soldier sucker and the desolder braid. What you have to do is get most of it off them heat what’s left and start to slide the board off the two big pins.
But there is where you have to be careful as it can lift the PCB tracks if not molten fully when you try to lift the board!
Also be careful soldering to the pins for flashing as they are very delicate and I almost buggered one up in the process.
When you have flashed, remove the ground to GPIO and restart the module to see if you see the WiFi AP. If all is ok, continue.
When done, resoldering is easy, just make sure it flows through to the back of the board. If you have a multimeter check the continuity from the mains pins to the board and check your solder joint carefully before reassembling. My solder joints were much better than what had been done by the manufacturer!
Good luck!

**Comment by SynAckFin** [comment]
Put your hammers away. https://github.com/codetheweb/tuyapi/issues/49#issuecomment-452512186

**Comment by servidge** [comment]
> 
> 
> Put your hammers away. [codetheweb/tuyapi#49 (comment)](https://github.com/codetheweb/tuyapi/issues/49#issuecomment-452512186)

well i guess that's worth a look. maybe with some adjustments. 
The SSID from my version of the Teckin SP22 v1.4 is "Smart-Life-xxxx" 
xxx=the last 4 digits of the mac of the device.

**Comment by Aterfax** [comment]
I can report complete success on the Teckin SP23 utilizing @SynAckFin 's Perl script and using the Sonoff BlitzWolf SHP2 config.

His script can be found here:

https://github.com/SynAckFin/TuyOTA

His detailled walk through here: https://github.com/SynAckFin/TuyOTA/wiki/Walkthrough

**Comment by servidge** [comment]
> 
> 
> I can report complete success on the Teckin SP23 utilizing @SynAckFin 's Perl script and using the Sonoff BlitzWolf SHP2 config.
> 
> His script can be found here:
> 
> https://github.com/SynAckFin/TuyOTA
> 
> His detailled walk through here: https://github.com/SynAckFin/TuyOTA/wiki/Walkthrough

Confirmation, the Teckin SP22 v1.4 can also be updated via ota update. My sawing work was unnecessary and is now obsolete. Thanks to @SynAckFin for his awesome work. 

For clarification: 
The plugs must be integrated to your own wifi.  (Normal setup like everyone else) 
The given IP from the walk through within the Command "sudo ./tuyota.pl -ip 192.168.31.45 -s MyHomeNet -p MySecret" should be the device IP from your plug. 
After this @Aterfax linked walk through from @SynAckFin works fine. 

Only the power readings need to be adjusted after the OTA update. 270 instead of 227 volt is yet a noticeable difference.

**Comment by Rodny9** [comment]
> > I can report complete success on the Teckin SP23 utilizing @SynAckFin 's Perl script and using the Sonoff BlitzWolf SHP2 config.
> > His script can be found here:
> > https://github.com/SynAckFin/TuyOTA
> > His detailled walk through here: https://github.com/SynAckFin/TuyOTA/wiki/Walkthrough
> 
> Confirmation, the Teckin SP22 v1.4 can also be updated via ota update. Set as Teckin (52) in Tasmota config. My sawing work was unnecessary and is now obsolete. Thanks to @SynAckFin for his awesome work.
> 
> For clarification:
> The plugs must be integrated to your own wifi. (Normal setup like everyone else)
> The given IP from the walk through within the Command "sudo ./tuyota.pl -ip 192.168.31.45 -s MyHomeNet -p MySecret" should be the device IP from your plug.
> After this @Aterfax linked walk through from @SynAckFin works fine.
> 
> Only the power readings need to be adjusted after the OTA update. 270 instead of 227 volt is yet a noticeable difference.

Thanks for your comment I didn't have to saw my plug lol. However, in the configuration I wasn't able to find the number 52 or nothing Teckin related. Which firmware have you flashed?

**Comment by servidge** [comment]
> Thanks for your comment I didn't have to saw my plug lol. However, in the configuration I wasn't able to find the number 52 or nothing Teckin related. Which firmware have you flashed?

I just clicked the start update button ;). After the OTA update and reboot the sonoff.bin Version 6.4.1 is active.

**Comment by Rodny9** [comment]
Ok, so you next updated it? Cause i have sonoff 6.2.1 installed by TuyOTA.

**Comment by spock64** [comment]
I managed to flash my Slitinto plugs using https://github.com/ct-Open-Source/tuya-convert (the now recommended method).

But, beware! You must ensure that you configure the unit type (as the Blitzwolf SHP2) at first boot with the new firmware and before the unit is restarted. If you don't and you manage to get the password wrong (or it contains an asterisk), the wifi will not connect and you cannot get wifimanager to work by the normal button presses - because the button is on GPIO 0 by default (he Slitinto button is on GPIO 13). The unit appears to be bricked - but it isn't - you just need to erase the flash, and flash again ...

So, hit up http://192.168.4.1/cn while connected to the plug's AP before configuring anything else - otherwise it is time for the hammer, soldering iron, etc.

Oddly enough, I have become adept with my rubber mallet!

**Comment by SynAckFin** [comment]
> I managed to flash my Slitinto plugs using https://github.com/ct-Open-Source/tuya-convert (the now recommended method).
> 
> But, beware! You must ensure that you configure the unit type (as the Blitzwolf SHP2) at first boot with the new firmware and before the unit is restarted. If you don't and you manage to get the password wrong (or it contains an asterisk), the wifi will not connect and you cannot get wifimanager to work by the normal button presses - because the button is on GPIO 0 by default (he Slitinto button is on GPIO 13). The unit appears to be bricked - but it isn't - you just need to erase the flash, and flash again ...
> 
> So, hit up http://192.168.4.1/cn while connected to the plug's AP before configuring anything else - otherwise it is time for the hammer, soldering iron, etc.
> 
> Oddly enough, I have become adept with my rubber mallet!

There is a simple solution to recovering when the password is incorrect that doesn't involve a rubber mallet.
1. Log into you WiFi access point
2. Remove the access point password so devices can connect without a password.
3. Power your device on. It will connect to the WiFi.
4. Connect to your device and correct the password.
5. Put the password back on your WiFi access point.

**Comment by spock64** [comment]
Hi, Yes I guess that would work - though there would be a little chaos when the AP password changed. There’s a lot of devices on the network!
Thanks for pointing this out :-)

**Comment by evaluationevaluation** [comment]
Hi,

just tried to flash my 2 Slitinto Model NX-SP202 (Dual Outlet) using tuya-convert.
Used VM-Ware image of Kali Linux 2019.1
Installed requirements using ./install_prereq-sh and installed missing npm using apt-get install npm

So far managed to flash one of the two with Tasmota image shipped with tuya-convert.

Now my 2 questions:
1) really don't know why the second does not want to get flashed. Tried the fast and slow blinking mode and restarted the start_flash.sh several times and waited quite long... nothing happens. The log files are fine and also observed the 4 different SCREEN sessions. My android connects well to the access point but this is the only reaction in the 4 SCREEN sessions.
Is there a possibility to find out why my second Slitinto does not connect?
Should I see the section "sending packets and waiting 60 seconds" every 60 seconds again? I see it only once...

2) What Tasmota configuration does you use for Slitinto Dual Outlets?
I selected "Generic (18)" as Module Type and found out that
* Button1 is on GPIO0
* Button2 is on GPIO16
* Relay1 is on GPIO15
* Relay2 is on GPIO14
But then I don't see metering information.
Do I need to flash a different Tasmota Version or is there a better "base module" to configure Slitinto devices?
In Tasmota WIKI "Templates" I saw example for Blitzwolf with GPIO5 selected as "BL0937", but in Generic Module I cannot select such a function.
What is the trick to get Slitinto fully working with 2xButtons,2xLEDs,2xRelays and Metering Sensors?

Your help is really appreciated and I want to thank everyone who can point me to the right direction or even give me the final solution.

**Comment by spock64** [comment]
Hi,

First, are you using the stop flash and then start flash script for the second and further units? This worked for me.

Second, as of version 6.4.1.17, Tasmota includes a “template” facility that does what you need - you can define your module pin by pin. See  https://github.com/arendst/Sonoff-Tasmota/wiki/Templates
Perhaps you could wait for the next release or build it yourself?

**Comment by evaluationevaluation** [comment]
Hi,

thank you very much for your quick answer.
Yes, I use stop_flash between the trials. Also rebooted the machine several times in between to be sure that all is fine again.

Will have a closer look at the template facility. Found the wiki article with the example of Blitzwolf and just wanted to select the mentioned entries in the web config...
Will try to find out if my knowledge is enough to create my own template and upload a custom made image... at least for the first of my modules.

Any further ideas to find out why my second item denies to get in contact with tuya-convert?
Do I have to take care about a special timing when starting tuya-convert or should it be sufficient to simply start tuya-convert, plug in the device and start blinking and just wait some minutes?
Can I see somewhere whether tuya-convert resends connection packages every 60 seconds or not?

**Comment by spock64** [comment]
To make the flash happen, the plug needs to be in the mode where the led blinks rapidly.
To get into this mode, the button needs to be held for a few seconds.
You may have been lucky that the first plug you tried was in that mode when first powered on - one of my six plugs was like this.
Also, remember to follow the instructions precisely and follow the sequence that is specified by the script - the start_flash, connect a Wi-Fi device to the temporary AP, then power on the plug. Hold the button if needed to get the led to blink rapidly.  The initial flash should complete within a few sips of your cup of tea / coffee. You can then load the firmware you need. Beware - the most recent firmware is bigger than 512k so you need the initial flash to be smaller than that!

**Comment by evaluationevaluation** [comment]
f**k, got contact by a trick but network connection had an issue and now the device blinks slowly without any other reaction. Button press does not seem to have an effect. Long press does not work anymore.
Did I brick it? Any trick to unbrick?

Trick was (and I'm convinced that this could help other people in getting in contact to the device):
* Installed tuya app
* input some one time mail account and created cloud account with it
* input some false family name and geolocation
* selected a 5G network and got error message that 5G is not supported
** but then you can paste the vtrust-flash SSID with password
* item then connected to tuya-convert and I quickly disconnected smarthome from network
* item began to flash
* unfortunately then I got some issue with networking (don't know what exactly occured)

Any ideas how to reactivate the device?

**Comment by evaluationevaluation** [comment]
just few more infos:
* device flashed a bit
** found dumped original firmware and device-info.txt


after got contact via the app trick I executed "curl http://10.42.42.42" and "curl http://10.42.42.42/flash3"
Did the same with the other plug if I remember well

**Comment by spock64** [comment]
Yes, the slow flash from Tasmota firmware means that it needs to be configured.

Glad you got things sorted.

**Comment by evaluationevaluation** [comment]
made my day!!! thought it was bricked but it's waiting for me to type in WIFI credentials by opening an Access Point... (and I already began to search my rubber hammer :) )

**Comment by erichegit** [comment]
For my Teckin SP22 the configuration Blitzwolf SHP2 is not working at all :-1: 
But the configuration Teckin (52) works fine.

If there wouldn`t be a much to high Voltage of 280 V (230V should be fine)

How can you manually adjust it?
Or how do you get correct Voltage values?
Wrong V results in wrong Power,...

**Comment by servidge** [comment]
> How can you manually adjust it?
> Or how do you get correct Voltage values?
> Wrong V results in wrong Power,...

A little bit of hardware or an unpatched Plug is helpful.
The steps are described in the wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Power-Monitoring-Calibration

**Comment by woody4165** [comment]
Hi @Clooney82 

I just flashed Tasmota using Tuya-Convert and all went fine.

I don't understand how to load the template you have in your first post.

> { "TECKIN SP22v1.4", // https://www.amazon.de/gp/product/B07D5V139R
> GPIO_USER, // GPIO00 Red Led (1 = On, 0 = Off)
> GPIO_KEY1, // GPIO01 Serial TXD and Button
> GPIO_USER, // GPIO02 Blue Led (1 = On, 0 = Off)
> GPIO_LED2_INV, // GPIO03 Serial RXD and Red Led (1 = On, 0 = Off)
> GPIO_HLW_CF, // GPIO04 BL0937 or HJL-01 CF power
> GPIO_HLW_CF1, // GPIO05 BL0937 or HJL-01 CF1 voltage / current
> 0, 0, 0, 0, 0, 0, // Flash connection
> GPIO_HLW_SEL, // GPIO12 BL0937 or HJL-01 Sel output
> GPIO_LED1_INV, // GPIO13 Blue Led (1 = On, 0 = Off)
> GPIO_REL1, // GPIO14 Relay (0 = Off, 1 = On)
> 0, 0, 0
> }


I flashed another smart plug (from Houzetek) and the template I used look like this

`{"NAME":"AWP07L","GPIO":[56,255,255,130,255,134,255,255,0,17,132,21,255],"FLAG":0,"BASE":18}
`
So, I don't understand how to load it into the "Configuration Other" on the Web UI.
Can you help me?

Thanks

**Comment by Frankster-NL** [comment]
I managed to open my first Teckin SP22 and the inside is fully similar to the photos in the first post of this thread. I now have a very noobish question; can I simply solder the wires to the main board or do I have to desolder the tywe2s first?
Reading this thread gives some conflicting messages...

**Comment by meingraham** [comment]
Looking at write-ups for flashing (regardless of firmware), it looks like you can flash "in place" without removing the module. Search `teckin sp22 flash` and see how others are going about it.

**Comment by Aterfax** [comment]
> 
> 
> I managed to open my first Teckin SP22 and the inside is fully similar to the photos in the first post of this thread. I now have a very noobish question; can I simply solder the wires to the main board or do I have to desolder the tywe2s first?
> Reading this thread gives some conflicting messages...

https://github.com/arendst/Sonoff-Tasmota/issues/3950#issuecomment-455004529

You can flash in place using any of the available methods based around the Sonoff Tasmota stuff above.

**Comment by meingraham** [comment]
Tuya-Convert - depending on the "newness" of your device. Newer devices are coming with patched Tuya firmware which disables the Tuya-Convert OTA flashing option.

**Comment by DonStefano** [comment]
> Tuya-Convert - depending on the "newness" of your device. Newer devices are coming with patched Tuya firmware which disables the Tuya-Convert OTA flashing option.

How can I find out which firmware version is installed without using the Chinese software?

**Comment by meingraham** [comment]
@DonStefano 

It's a Catch22. To see what Tuya version is on the device you have to connect to their app. However, if you connect to their app, it will upgrade to the latest Tuya firmware without asking... thus no longer able to use Tuya-Convert.

The best way to know if Tuya-Convert works is to try it on your device right out of the box. If it displays nothing bu a never ending string of periods `...............`, then it has the patched Tuya firmware.

Mike

**Comment by SynAckFin** [comment]
@meingraham 
I've recently bought a Tuya thermostat and it uses SSL to communicate with the tuya servers so I assume this is what the newer firmware is doing.
I looked at modifying the OTA scripts to handle this but unfortunately the SSL connection uses a pre-shared key and without that key there isn't anything I can do.
If I knew where I could get a copy of the firmware I might be able to extract the key and get the OTA scripts working again.

**Comment by meingraham** [comment]
@SynAckFin @DonStefano 

Well, there's recent activity as of late last night that there may be some progress on Tuya-Convert which can circumvent the patched Tuya firmware. Some work left to do to update documentation and installation procedures. That should be ready soon.

Having said that, there are also some users reporting that some newer versions of the Teckin SP22 are coming with a WR2 WiFi module which is based on an RTL8710BN chip (i.e., NOT ESP82xx)! The Teckin SP22 also comes branded as  BlitzWolf BW-SHP2 and HomeCube SP1.

Finally, for any ESP82xx based device, once it is in programming mode, the firmware that is on-board can be [downloaded](https://github.com/arendst/Sonoff-Tasmota/wiki/Flashing#optional-backup-firmware) (i.e., backed up).

Mike

**Comment by Frankster-NL** [comment]
@meingraham any hint on where I can find that new version? The tuya-convert GitHub does not indicate anything on this...

**Comment by meingraham** [comment]
@Frankster-NL 

`Some work left to do to update documentation and installation procedures. That should be ready soon.`

I would think that there should be something ready by the beginning of the week.

I did see that the current process took more that one attempt to finally complete successfully and that so far light bulbs are still not being flashed. This sounds reminiscent of the original work. It took a bit of refinement. This will probably take a bit of time to "smooth out".

**Comment by DonStefano** [comment]
That looks promising. I will prepare the hardware during weekend that I can try soon after release. I have to find out if they have the wrong Wifi module so I can send them back in case.

**Comment by baldfox** [comment]
For those of you looking to flash teckin SP22, here's what I did to get mine working with OTA convert 2!
some pointers:
1) to put it in pairing mode, i plugged it in (the light was off) and I held it down for about 6 seconds... the light was blinking blue and off, not red and blue (I tried many times with red and blue flashing but it wouldn't work for some reason).

2) I followed this video - https://www.youtube.com/watch?v=6_IZEa9JcC8
I also manually installed libssl-dev

3) I left my original tuya convert folder and just opened a new folder on the raspberry pi...

4) I cloned this repository into it:
https://github.com/M4dmartig4n/tuya-convert

Follow the instructions in the vid...

5) The lights went out on the teckin SP22 and i thought it had messed up, but it just worked. You need to be patient.

Then I proceeded to flash using the curl commands...
Hopefully this helps, it's not the cleanest instructions, but it worked for me. My bricked SP22 is now in Home Assistant :)

**Comment by ddppddpp** [comment]
there's a working fork for all your sp22 ;-) [https://github.com/ct-Open-Source/tuya-convert/issues/273](url)

**Comment by DonStefano** [comment]
> @DonStefano
> 
> It's a Catch22. To see what Tuya version is on the device you have to connect to their app. However, if you connect to their app, it will upgrade to the latest Tuya firmware without asking... thus no longer able to use Tuya-Convert.
> 
> The best way to know if Tuya-Convert works is to try it on your device right out of the box. If it displays nothing bu a never ending string of periods `...............`, then it has the patched Tuya firmware.
Thank you Mike!

Today I was able to flash all my 4 Teckin SP22 bought 2 Weeks ago from Amazon.de

Cheers,
Stefan

**Comment by rafuz** [comment]
Tuya convert also works with Slitinto SP202, even with new firmware.

**Comment by arannothc** [comment]
> @Clooney82, did you find a non-destructive way to open them up?

yes, i successfully opened it without destroying, just left some minor marks. 

I used a flat screw driver and some opening picks.

**Comment by Frankster-NL** [comment]
If I may suggest something; opening the SP22 is very easy if you use a rubber hammer. Simply hit (not too hard, but harder than you think) the glued rim from the side. After a few blows you will see both parts separating. It leaves no marks whatsoever.

**Comment by devTechi** [comment]
@Frankster-NL 

that really works, just did it 😃
